class TextConst {
  const TextConst._();

  static const todo = 'To Do';
  static const startDesc1 = 'A productivity helper to manage your daily task.';
  static const startDesc2 = 'Make it a habit to coordinate your task.';
  static const startDesc3 = 'Remember everything and get things done!';
  static const greeting = 'Hi there!\nWhat should we call you?';
  static const youCanCallMe = 'You can call me...';
  static const getStarted = 'Get started';
  static const proceed = 'Proceed';
  static const welcome = 'Welcome';
  static const today = 'Today';
  static const completed = 'completed';
  static const veryImportant = 'Very Important';
  static const important = 'Important';
  static const partImportant = 'Partially Important';
  static const upcoming = 'Upcoming';
  static const taskName = 'Task name';
  static const description = 'Description';
  static const date = 'Date';
  static const importance = 'Importance';
  static const rescheduleToday = 'Reschedule to Today';
  static const addTask = 'Add task';
  static const enterName = 'Please enter your name to proceed';
  static const inputTaskTitle = 'Please enter your task\'s title';
  static const inputTaskDate = 'Please input the task\'s date';
  static const inputTaskImportance = 'Please input the task\'s importance';
  static const taskDeleted = 'Task deleted!';
  static const markIncomplete = 'Mark as Incomplete';
  static const markComplete = 'Mark as Completed';
  static const successMakeChanges = 'Successfully make changes!';
  static const confirmDeleteTask =
      'Are you sure you would like to delete this task?';

  static const showcaseCalendarView =
      'You can click here to show Calendar overview';
  static const showcaseTaskTitleField =
      'Here is the field to put your task title';
  static const showcaseTaskDescField =
      'Here is the field to put your task description';
  static const showcaseDate = 'Choose the date of your task';
  static const showcaseimportance = 'Select the importance of your task';
  static const showcaseTitle = 'This is a preview task generated by Philip.';
  static const showcaseDesc =
      'This is a preview task description generated by Philip.';
  static const showcaseSaveTaskBtn = 'Click Save task & preview the next page';
  static const showcaseEditTaskBtn = 'Press here to edit your task';
  static const showcaseDeleteTaskBtn = 'Press here to delete your task';
  static const showcaseTaskCompletion =
      'Click here to make changes on the task completion';
  static const showcaseAddTask = 'Click here to add task';
}
